import type { DemoScenarioData } from "../contracts";

const northstarTenant = {
  id: "tenant_northstar_retail",
  name: "Northstar Retail",
  slug: "northstar-retail",
} as const;

const catalogManagerCapabilities = [
  "catalog.import:create",
  "catalog.product:read",
  "catalog.review:read",
  "catalog.review:decide",
  "catalog.approval:execute",
  "evaluation.run:read",
  "audit.event:read",
] as const;

export const northstarRetailScenario = {
  id: "northstar-retail",
  session: {
    actor: {
      id: "user_northstar_maya_chen",
      name: "Maya Chen",
      email: "maya.chen@northstar.example",
    },
    activeTenant: northstarTenant,
    memberships: [
      {
        tenant: northstarTenant,
        role: "catalog_manager",
        allowedCapabilities: catalogManagerCapabilities,
      },
    ],
    role: "catalog_manager",
    allowedCapabilities: catalogManagerCapabilities,
  },
  dashboard: {
    metricCards: [
      {
        id: "metric_ns_products_indexed",
        label: "Products indexed",
        value: "18,420",
        status: "ready",
        sourceContext: "Catalog projection idx_catalog_v2026_07_10",
        trendLabel: "+412 from latest supplier import",
      },
      {
        id: "metric_ns_supplier_rows",
        label: "Supplier rows processed",
        value: "2,184",
        status: "partial_success",
        sourceContext: "North Audio Wholesale import imp_ns_2026_07_10_001",
        trendLabel: "37 rows need correction",
      },
      {
        id: "metric_ns_review_open",
        label: "Open duplicate reviews",
        value: "12",
        status: "review_required",
        sourceContext: "Matching config match_cfg_m2_demo_v1",
        trendLabel: "4 high risk",
      },
      {
        id: "metric_ns_search_quality",
        label: "Demo search quality",
        value: "nDCG@10 0.82",
        status: "ready",
        sourceContext: "Demo evaluation run eval_ns_2026_07_10_r01",
      },
    ],
    recentImports: [
      {
        id: "imp_ns_2026_07_10_001",
        source: "north-audio-wholesale-july.csv",
        supplierName: "North Audio Wholesale",
        status: "partial_success",
        submittedAt: "2026-07-10T14:04:00Z",
        completedAt: "2026-07-10T14:19:38Z",
        rowCounts: {
          total: 842,
          accepted: 805,
          normalized: 798,
          rejected: 37,
          reviewCandidates: 9,
        },
        searchableState: "partially_searchable",
        failureSummary: "37 rows rejected for missing GTIN or unsupported currency.",
      },
      {
        id: "imp_ns_2026_07_09_002",
        source: "metro-electronics-accessories.csv",
        supplierName: "Metro Electronics",
        status: "indexed",
        submittedAt: "2026-07-09T18:22:11Z",
        completedAt: "2026-07-09T18:36:45Z",
        rowCounts: {
          total: 516,
          accepted: 516,
          normalized: 516,
          rejected: 0,
          reviewCandidates: 3,
        },
        searchableState: "searchable",
      },
      {
        id: "imp_ns_2026_07_08_001",
        source: "urban-home-supply-office.csv",
        supplierName: "Urban Home Supply",
        status: "failed",
        submittedAt: "2026-07-08T09:15:24Z",
        completedAt: "2026-07-08T09:16:09Z",
        rowCounts: {
          total: 214,
          accepted: 0,
          normalized: 0,
          rejected: 214,
          reviewCandidates: 0,
        },
        searchableState: "blocked",
        failureSummary: "Header validation failed: required manufacturer_part_number column missing.",
      },
    ],
    feedHealth: [
      {
        id: "feed_ns_north_audio",
        source: "North Audio Wholesale",
        status: "review_required",
        lastReceivedAt: "2026-07-10T14:04:00Z",
        detail: "Latest feed indexed with duplicate-review candidates and row rejects.",
      },
      {
        id: "feed_ns_metro_electronics",
        source: "Metro Electronics",
        status: "ready",
        lastReceivedAt: "2026-07-09T18:22:11Z",
        detail: "Accessory feed searchable with no rejected rows.",
      },
      {
        id: "feed_ns_urban_home",
        source: "Urban Home Supply",
        status: "failed",
        lastReceivedAt: "2026-07-08T09:15:24Z",
        detail: "Office accessories feed blocked by schema validation.",
      },
    ],
    pipelineStages: [
      {
        id: "stage_ns_ingestion",
        label: "Ingestion",
        status: "partial_success",
        processedCount: 1565,
        issueCount: 37,
      },
      {
        id: "stage_ns_normalization",
        label: "Normalization",
        status: "ready",
        processedCount: 1314,
        issueCount: 7,
      },
      {
        id: "stage_ns_matching",
        label: "Duplicate matching",
        status: "review_required",
        processedCount: 1314,
        issueCount: 12,
      },
      {
        id: "stage_ns_indexing",
        label: "Search indexing",
        status: "processing",
        processedCount: 1277,
        issueCount: 0,
      },
    ],
    reviewSummary: {
      open: 12,
      highRisk: 4,
      assignedToMe: 6,
      oldestOpenAge: "2d 4h",
    },
    reviewCases: [
      {
        caseId: "rev_ns_dup_sony_wh1000xm5_001",
        tenantId: "tenant_northstar_retail",
        status: "unresolved",
        risk: "high",
        proposal: "merge_duplicate",
        confidence: 0.94,
        reasonCodes: ["gtin_match", "mpn_match", "title_similarity", "price_delta_caution"],
        sourceImportId: "imp_ns_2026_07_10_001",
        sourceSupplier: "North Audio Wholesale",
        age: "18h",
        assignee: "Maya Chen",
        title: "Sony WH-1000XM5 duplicate candidate",
      },
      {
        caseId: "rev_ns_dup_anker_737_001",
        tenantId: "tenant_northstar_retail",
        status: "unresolved",
        risk: "medium",
        proposal: "merge_duplicate",
        confidence: 0.89,
        reasonCodes: ["brand_match", "mpn_match", "capacity_match"],
        sourceImportId: "imp_ns_2026_07_09_002",
        sourceSupplier: "Metro Electronics",
        age: "1d 7h",
        assignee: "Unassigned",
        title: "Anker 737 Power Bank duplicate candidate",
      },
      {
        caseId: "rev_ns_variant_bose_qc_ultra_001",
        tenantId: "tenant_northstar_retail",
        status: "deferred",
        risk: "medium",
        proposal: "mark_variant",
        confidence: 0.76,
        reasonCodes: ["brand_match", "title_similarity", "color_conflict"],
        sourceImportId: "imp_ns_2026_07_10_001",
        sourceSupplier: "North Audio Wholesale",
        age: "2d 4h",
        assignee: "Maya Chen",
        title: "Bose QuietComfort Ultra color variant review",
      },
    ],
    evaluationSummary: {
      manifestId: "manifest_m2_duplicate_review_demo_v1",
      runId: "eval_ns_2026_07_10_r01",
      configurationId: "retrieval_hybrid_cfg_m2_demo_v1",
      status: "demo_data",
      evaluatedAt: "2026-07-10T15:05:12Z",
      metrics: [
        {
          id: "metric_eval_ndcg10",
          label: "Search nDCG@10",
          value: "0.82",
          baselineValue: "0.74 lexical baseline",
          delta: "+0.08",
        },
        {
          id: "metric_eval_duplicate_precision",
          label: "Duplicate precision@5",
          value: "0.91",
          baselineValue: "0.86 rules baseline",
          delta: "+0.05",
        },
        {
          id: "metric_eval_review_recall",
          label: "Review candidate recall",
          value: "0.88",
          baselineValue: "0.81 rules baseline",
          delta: "+0.07",
        },
      ],
      baselineComparison:
        "Demo fixture compares hybrid retrieval and matching against a lexical/rules baseline.",
      demoDataNotice:
          "Demo evaluation data; not a verified production measurement.",
    },
    auditEvents: [
      {
        id: "audit_ns_2026_07_10_003",
        timestamp: "2026-07-10T14:20:02Z",
        actor: "Maya Chen",
        tenant: northstarTenant,
        action: "catalog.import.completed_partial",
        target: "imp_ns_2026_07_10_001",
        metadata: ["805 accepted rows", "37 rejected rows", "9 review candidates"],
      },
      {
        id: "audit_ns_2026_07_10_002",
        timestamp: "2026-07-10T14:18:41Z",
        actor: "System",
        tenant: northstarTenant,
        action: "review.case.created",
        target: "rev_ns_dup_sony_wh1000xm5_001",
        metadata: ["proposal merge_duplicate", "confidence 0.94", "human approval required"],
      },
      {
        id: "audit_ns_2026_07_09_001",
        timestamp: "2026-07-09T18:37:03Z",
        actor: "System",
        tenant: northstarTenant,
        action: "search.index.updated",
        target: "idx_catalog_v2026_07_10",
        metadata: ["Metro Electronics accessory rows searchable", "tenant scoped projection"],
      },
    ],
  },
  reviewCases: [
    {
      summary: {
        caseId: "rev_ns_dup_sony_wh1000xm5_001",
        tenantId: "tenant_northstar_retail",
        status: "unresolved",
        risk: "high",
        proposal: "merge_duplicate",
        confidence: 0.94,
        reasonCodes: ["gtin_match", "mpn_match", "title_similarity", "price_delta_caution"],
        sourceImportId: "imp_ns_2026_07_10_001",
        sourceSupplier: "North Audio Wholesale",
        age: "18h",
        assignee: "Maya Chen",
        title: "Sony WH-1000XM5 duplicate candidate",
      },
      recordA: {
        id: "prd_ns_supplier_naw_sony_wh1000xm5_black",
        supplier: "North Audio Wholesale",
        supplierSku: "NAW-SONY-WH1000XM5-BLK",
        title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones - Black",
        brand: "Sony",
        category: "Headphones",
        gtin: "027242923553",
        manufacturerPartNumber: "WH1000XM5/B",
        price: 299.99,
        currency: "USD",
        color: "Black",
        connectivity: "Bluetooth",
        sourceImportId: "imp_ns_2026_07_10_001",
      },
      recordB: {
        id: "prd_ns_canonical_sony_wh1000xm5_black",
        supplier: "Northstar Canonical Catalog",
        supplierSku: "NS-AUDIO-000482",
        title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
        brand: "Sony",
        category: "Headphones",
        gtin: "027242923553",
        manufacturerPartNumber: "WH-1000XM5/B",
        price: 328.0,
        currency: "USD",
        color: "Black",
        connectivity: "Bluetooth",
        sourceImportId: "imp_ns_seed_catalog_2026_07_01",
      },
      provenance: [
        {
          field: "gtin",
          source: "North Audio Wholesale",
          sourceImportId: "imp_ns_2026_07_10_001",
          sourceRow: 118,
          observedAt: "2026-07-10T14:06:18Z",
        },
        {
          field: "manufacturerPartNumber",
          source: "Northstar Canonical Catalog",
          sourceImportId: "imp_ns_seed_catalog_2026_07_01",
          sourceRow: 482,
          observedAt: "2026-07-01T12:00:00Z",
        },
        {
          field: "price",
          source: "North Audio Wholesale",
          sourceImportId: "imp_ns_2026_07_10_001",
          sourceRow: 118,
          observedAt: "2026-07-10T14:06:18Z",
        },
      ],
      rawNormalizedCanonical: [
        {
          field: "title",
          rawValue: "SONY WH1000XM5 WIRELESS NC HEADPHONES BLACK",
          normalizedValue: "Sony WH-1000XM5 Wireless Noise Canceling Headphones - Black",
          canonicalValue: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
        },
        {
          field: "manufacturer_part_number",
          rawValue: "WH1000XM5B",
          normalizedValue: "WH1000XM5/B",
          canonicalValue: "WH-1000XM5/B",
        },
        {
          field: "gtin",
          rawValue: "27242923553",
          normalizedValue: "027242923553",
          canonicalValue: "027242923553",
        },
        {
          field: "price",
          rawValue: "299.99 USD",
          normalizedValue: "299.99 USD",
          canonicalValue: "328.00 USD",
        },
      ],
      conflicts: [
        {
          field: "price",
          recordAValue: "299.99 USD",
          recordBValue: "328.00 USD",
          severity: "medium",
          note: "Supplier cost changed enough to require reviewer awareness before approval.",
        },
        {
          field: "title",
          recordAValue: "Includes Black color suffix",
          recordBValue: "Canonical title omits color suffix",
          severity: "low",
          note: "Color is preserved as a structured attribute in the merge proposal.",
        },
      ],
      signals: [
        {
          id: "signal_ns_gtin_exact",
          label: "GTIN exact match",
          value: "027242923553",
          weight: "supporting",
          explanation: "Both records resolve to the same normalized GTIN.",
        },
        {
          id: "signal_ns_mpn_normalized",
          label: "Manufacturer part number normalized match",
          value: "WH-1000XM5/B",
          weight: "supporting",
          explanation: "Punctuation differs in raw input but normalizes to the same Sony part number.",
        },
        {
          id: "signal_ns_title_similarity",
          label: "Title similarity",
          value: "0.96 cosine similarity",
          weight: "supporting",
          explanation: "Token overlap covers brand, model, product type, and wireless noise canceling attributes.",
        },
        {
          id: "signal_ns_price_delta",
          label: "Price delta",
          value: "8.5% lower supplier price",
          weight: "caution",
          explanation: "Price movement is plausible but requires human approval before merge execution.",
        },
      ],
      approvalContext: {
        required: true,
        operationId: "op_demo_ns_merge_sony_wh1000xm5_20260710",
        requiredCapability: "catalog.approval:execute",
        allowedForCurrentRole: true,
        message:
          "Approving this prototype result records local UI state only; no server-side catalog mutation occurs.",
      },
      auditPreview: {
        action: "approval.duplicate_merge.requested",
        target: "prd_ns_canonical_sony_wh1000xm5_black",
        metadata: [
          "source prd_ns_supplier_naw_sony_wh1000xm5_black",
          "operation op_demo_ns_merge_sony_wh1000xm5_20260710",
          "confidence 0.94",
          "human approval required",
        ],
      },
      evaluationContext: {
        label: "Demo duplicate-review evaluation context",
        runId: "eval_ns_2026_07_10_r01",
        manifestId: "manifest_m2_duplicate_review_demo_v1",
        configurationId: "match_cfg_m2_demo_v1",
        status: "demo_data",
        metricNotes: [
          "Precision@5 0.91 in deterministic fixture context.",
          "Price delta signal is shown as caution rather than merge proof.",
          "Metrics are demo labels for frontend evidence layout only.",
        ],
      },
    },
  ],
} as const satisfies DemoScenarioData;
